apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kubeguard.fullname" . }}-pdb
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "kubeguard.name" . }}
    app.kubernetes.io/component: security-scanner
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kubeguard.name" . }}
      app.kubernetes.io/component: security-scanner