apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubeguard.fullname" . }}-postgres
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "kubeguard.name" . }}-postgres
    app.kubernetes.io/component: database
spec:
  replicas: {{ .Values.postgres.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kubeguard.name" . }}-postgres
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kubeguard.name" . }}-postgres
        app.kubernetes.io/component: database
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "kubeguard.fullname" . }}-secrets
                  key: DB_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          resources:
            requests:
              memory: {{ .Values.postgres.resources.requests.memory }}
              cpu: {{ .Values.postgres.resources.requests.cpu }}
            limits:
              memory: {{ .Values.postgres.resources.limits.memory }}
              cpu: {{ .Values.postgres.resources.limits.cpu }}
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.postgres.user }}
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.postgres.user }}
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: {{ include "kubeguard.fullname" . }}-postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeguard.fullname" . }}-postgres
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "kubeguard.name" . }}-postgres
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/name: {{ include "kubeguard.name" . }}-postgres
    app.kubernetes.io/component: database

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kubeguard.fullname" . }}-postgres-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "kubeguard.name" . }}-postgres
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}