package io.github.mvrao94.kubeguard.rules;

public enum RuleCategory {
  SECURITY_CONTEXT,
  NETWORK_SECURITY,
  RBAC,
  SECRETS_MANAGEMENT,
  RESOURCE_LIMITS,
  IMAGE_SECURITY,
  POD_SECURITY,
  ADMISSION_CONTROL,
  AUDIT_LOGGING,
  COMPLIANCE,
  CONFIGURATION,
  VULNERABILITY
}
