apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeguard-config
  namespace: kubeguard
  labels:
    app.kubernetes.io/name: kubeguard
    app.kubernetes.io/component: security-scanner
data:
  application.yml: |
    server:
      port: 8080
    
    spring:
      application:
        name: kubeguard
      profiles:
        active: kubernetes
      
      datasource:
        url: jdbc:postgresql://kubeguard-postgres:5432/kubeguard
        username: kubeguard
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
      
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: false
    
    logging:
      level:
        com.kubeguard: INFO
        root: WARN
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] - %msg%n"
    
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
      endpoint:
        health:
          show-details: always
    
    kubeguard:
      security:
        rules:
          enabled: true
          strict-mode: false
      scan:
        max-concurrent: 10
        timeout-minutes: 30
        cleanup-days: 7
